import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Routes, Route } from "react-router-dom";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Modify app/layout.js to add a simple navigation bar
  // with links to Home (/), About (/about), and Login(/login)
  return (
   <html lang="en">
      <body>
        <nav>
          <ul>
            <li><Link href={"/"}>Home</Link></li>
            <li><Link href={"/about"}>About</Link></li>
            <li><Link href={"/login"}>Login</Link></li>
            <li><Link href={"/user/456"}>User</Link></li>
          </ul>
        </nav>
        {children}  {/* The actual page content goes here */}
        <footer>This footer appears on EVERY page</footer>
      </body>
    </html>
  );
}
